version: '3.1'

volumes:
    grafana_data: {}

networks:
  back-tier:
    external:
      name: simple-prometheus-monitoring_back-tier

services:
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - back-tier
