version: '3.1'

volumes:
    grafana_data: {}

networks:
  back-tier:
    external:
      name: simple-prometheus-monitoring_back-tier

services:
  nginx:
    image: hypoport/nginx-vts
    networks:
      - back-tier
    hostname: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80
  nginx-exporter:
    image: sophos/nginx-vts-exporter
    depends_on:
      - nginx
    networks:
      - back-tier
    hostname: nginx-exporter
    environment:
      - NGINX_STATUS=http://nginx/status/format/json
    ports:
      - 9913:9913
